// Import global CSS and Google font
import "./css/style.css"
import { Inter } from "next/font/google"
import Header from "@/components/ui/header"
import Banner from "@/components/banner"
import { ClerkProvider } from "@clerk/nextjs"

// Setting up the Inter font with specific subsets and display options
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap"
})

// Metadata for the page
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

// Root layout component
export default function RootLayout({ children }) {
  return (
    // Wrap the entire application with ClerkProvider
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body
          className={`${inter.variable} font-inter antialiased bg-white text-gray-900 tracking-tight`}
        >
          {/* Main layout structure */}
          <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
            
            {children}  {/* Render child components (page content) */}
            
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}